export type Era = "swsh" | "sv" | "mep";

export type ETB = {
  year: number;
  monthNum: number;
  month: string;
  setName: string;
  setId: string;
  promoName: string;
  promoNum: string;
  promoSetId: string;
  promoCardNum: string;
  pcEtbUrl: string;
  pcPromoUrl: string;
  notes: string;
  era: Era;
};

const PC = "https://www.pricecharting.com/game";

function eraOf(setId: string): Era {
  if (setId.startsWith("swsh") || setId === "cel25" || setId === "pgo") return "swsh";
  if (setId.startsWith("me")) return "mep";
  return "sv";
}

const RAW: Omit<ETB, "era">[] = [
  { year: 2021, monthNum: 2,  month: "February",  setName: "Shining Fates",         setId: "swsh45",    promoName: "Eevee VMAX",              promoNum: "SWSH087", promoSetId: "swshp", promoCardNum: "SWSH087", pcEtbUrl: `${PC}/pokemon-shining-fates/elite-trainer-box`,              pcPromoUrl: `${PC}/pokemon-promo/eevee-vmax-swsh087`, notes: "Special set, no booster boxes." },
  { year: 2021, monthNum: 3,  month: "March",     setName: "Battle Styles (Rapid Strike)", setId: "swsh5",     promoName: "Empoleon V",              promoNum: "SWSH079", promoSetId: "swshp", promoCardNum: "SWSH079", pcEtbUrl: `${PC}/pokemon-battle-styles/elite-trainer-box-rapid-strike-urshifu`, pcPromoUrl: "", notes: "Rapid Strike Urshifu variant. First alt-art secret rare set." },
  { year: 2021, monthNum: 6,  month: "June",      setName: "Chilling Reign",        setId: "swsh6",     promoName: "Calyrex V",               promoNum: "SWSH131", promoSetId: "swshp", promoCardNum: "SWSH131", pcEtbUrl: `${PC}/pokemon-chilling-reign/elite-trainer-box-pokemon-center-shadow-rider`, pcPromoUrl: "", notes: "Shadow Rider variant." },
  { year: 2021, monthNum: 8,  month: "August",    setName: "Evolving Skies (Vaporeon)", setId: "swsh7",     promoName: "Rayquaza V",              promoNum: "SWSH172", promoSetId: "swshp", promoCardNum: "SWSH172", pcEtbUrl: `${PC}/pokemon-evolving-skies/elite-trainer-box-vaporeon-pokemon-center`, pcPromoUrl: "", notes: "Vaporeon Pokemon Center variant. Umbreon VMAX 215 is THE chase." },
  { year: 2021, monthNum: 10, month: "October",   setName: "Celebrations",          setId: "cel25",     promoName: "Greninja Star",           promoNum: "SWSH144", promoSetId: "swshp", promoCardNum: "SWSH144", pcEtbUrl: `${PC}/pokemon-celebrations/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/greninja-star-swsh144`, notes: "25th anniversary set." },
  { year: 2021, monthNum: 11, month: "November",  setName: "Fusion Strike",         setId: "swsh8",     promoName: "Mew V",                   promoNum: "SWSH215", promoSetId: "swshp", promoCardNum: "SWSH215", pcEtbUrl: `${PC}/pokemon-fusion-strike/elite-trainer-box-pokemon-center`, pcPromoUrl: "", notes: "Largest SWSH set (284 cards)." },
  { year: 2022, monthNum: 2,  month: "February",  setName: "Brilliant Stars",       setId: "swsh9",     promoName: "Arceus V",                promoNum: "SWSH204", promoSetId: "swshp", promoCardNum: "SWSH204", pcEtbUrl: `${PC}/pokemon-brilliant-stars/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/arceus-v-swsh204`, notes: "Introduced VSTAR mechanic." },
  { year: 2022, monthNum: 5,  month: "May",       setName: "Astral Radiance",       setId: "swsh10",    promoName: "Hisuian Decidueye V",     promoNum: "SWSH226", promoSetId: "swshp", promoCardNum: "SWSH226", pcEtbUrl: `${PC}/pokemon-astral-radiance/elite-trainer-box-pokemon-center`, pcPromoUrl: "", notes: "Hisuian forms set; 3 PC ETB variants." },
  { year: 2022, monthNum: 7,  month: "July",      setName: "Pokemon GO",            setId: "pgo",       promoName: "Mewtwo V",                promoNum: "SWSH229", promoSetId: "swshp", promoCardNum: "SWSH229", pcEtbUrl: `${PC}/pokemon-go/elite-trainer-box`, pcPromoUrl: `${PC}/pokemon-promo/mewtwo-v-swsh229`, notes: "Pokemon GO crossover." },
  { year: 2022, monthNum: 9,  month: "September", setName: "Lost Origin",           setId: "swsh11",    promoName: "Giratina V",              promoNum: "SWSH265", promoSetId: "swshp", promoCardNum: "SWSH265", pcEtbUrl: `${PC}/pokemon-lost-origin/elite-trainer-box-pokemon-center`, pcPromoUrl: "", notes: "" },
  { year: 2022, monthNum: 11, month: "November",  setName: "Silver Tempest",        setId: "swsh12",    promoName: "Lugia V",                 promoNum: "SWSH267", promoSetId: "swshp", promoCardNum: "SWSH267", pcEtbUrl: `${PC}/pokemon-silver-tempest/elite-trainer-box-pokemon-center`, pcPromoUrl: "", notes: "Final main SWSH set." },
  { year: 2023, monthNum: 1,  month: "January",   setName: "Crown Zenith",          setId: "swsh12pt5", promoName: "Lucario VSTAR",           promoNum: "SWSH291", promoSetId: "swshp", promoCardNum: "SWSH291", pcEtbUrl: `${PC}/pokemon-crown-zenith/elite-trainer-box-plus`, pcPromoUrl: `${PC}/pokemon-promo/lucario-vstar-swsh291`, notes: "ETB Plus. First 'bonus' promo - precursor to SV stamped era." },
  { year: 2023, monthNum: 3,  month: "March",     setName: "Scarlet & Violet",      setId: "sv1",       promoName: "Koraidon",                promoNum: "SVP014",  promoSetId: "svp",   promoCardNum: "14",  pcEtbUrl: `${PC}/pokemon-scarlet-violet/elite-trainer-box-pokemon-center-koraidon`, pcPromoUrl: `${PC}/pokemon-promo/koraidon-pokemon-center-14`, notes: "Koraidon variant - first PC stamped era." },
  { year: 2023, monthNum: 3,  month: "March",     setName: "Scarlet & Violet",      setId: "sv1",       promoName: "Miraidon",                promoNum: "SVP013",  promoSetId: "svp",   promoCardNum: "13",  pcEtbUrl: `${PC}/pokemon-scarlet-violet/elite-trainer-box-pokemon-center-miraidon`, pcPromoUrl: `${PC}/pokemon-promo/miraidon-pokemon-center-13`, notes: "Miraidon variant." },
  { year: 2023, monthNum: 6,  month: "June",      setName: "Paldea Evolved",        setId: "sv2",       promoName: "Pikachu",                 promoNum: "SVP027",  promoSetId: "svp",   promoCardNum: "27",  pcEtbUrl: `${PC}/pokemon-paldea-evolved/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/pikachu-pokemon-center-27`, notes: "" },
  { year: 2023, monthNum: 8,  month: "August",    setName: "Obsidian Flames",       setId: "sv3",       promoName: "Charmander",              promoNum: "SVP044",  promoSetId: "svp",   promoCardNum: "44",  pcEtbUrl: `${PC}/pokemon-obsidian-flames/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/charmander-pokemon-center-44`, notes: "Charmander promo went viral." },
  { year: 2023, monthNum: 9,  month: "September", setName: "151",                   setId: "sv3pt5",    promoName: "Snorlax",                 promoNum: "SVP051",  promoSetId: "svp",   promoCardNum: "51",  pcEtbUrl: `${PC}/pokemon-scarlet-&-violet-151/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/snorlax-pokemon-center-51`, notes: "151 set is going out of print - prices rising." },
  { year: 2023, monthNum: 11, month: "November",  setName: "Paradox Rift",          setId: "sv4",       promoName: "Scream Tail",             promoNum: "SVP065",  promoSetId: "svp",   promoCardNum: "65",  pcEtbUrl: `${PC}/pokemon-paradox-rift/elite-trainer-box-pokemon-center-roaring-moon`, pcPromoUrl: `${PC}/pokemon-promo/scream-tail-pokemon-center-65`, notes: "Roaring Moon variant." },
  { year: 2023, monthNum: 11, month: "November",  setName: "Paradox Rift",          setId: "sv4",       promoName: "Iron Bundle",             promoNum: "SVP066",  promoSetId: "svp",   promoCardNum: "66",  pcEtbUrl: `${PC}/pokemon-paradox-rift/elite-trainer-box-pokemon-center-iron-valiant`, pcPromoUrl: `${PC}/pokemon-promo/iron-bundle-pokemon-center-66`, notes: "Iron Valiant variant." },
  { year: 2024, monthNum: 1,  month: "January",   setName: "Paldean Fates",         setId: "sv4pt5",    promoName: "Mimikyu",                 promoNum: "SVP075",  promoSetId: "svp",   promoCardNum: "75",  pcEtbUrl: `${PC}/pokemon-paldean-fates/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/mimikyu-pokemon-center-75`, notes: "ETB had massive 332% appreciation." },
  { year: 2024, monthNum: 3,  month: "March",     setName: "Temporal Forces",       setId: "sv5",       promoName: "Flutter Mane",            promoNum: "SVP097",  promoSetId: "svp",   promoCardNum: "97",  pcEtbUrl: `${PC}/pokemon-temporal-forces/elite-trainer-box-pokemon-center-iron-leaves`, pcPromoUrl: `${PC}/pokemon-promo/flutter-mane-pokemon-center-97`, notes: "Iron Leaves variant." },
  { year: 2024, monthNum: 3,  month: "March",     setName: "Temporal Forces",       setId: "sv5",       promoName: "Iron Thorns",             promoNum: "SVP098",  promoSetId: "svp",   promoCardNum: "98",  pcEtbUrl: `${PC}/pokemon-temporal-forces/elite-trainer-box-pokemon-center-walking-wake`, pcPromoUrl: `${PC}/pokemon-promo/iron-thorns-pokemon-center-98`, notes: "Walking Wake variant." },
  { year: 2024, monthNum: 5,  month: "May",       setName: "Twilight Masquerade",   setId: "sv6",       promoName: "Teal Mask Ogerpon",       promoNum: "SVP123",  promoSetId: "svp",   promoCardNum: "123", pcEtbUrl: `${PC}/pokemon-twilight-masquerade/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/teal-mask-ogerpon-pokemon-center-123`, notes: "" },
  { year: 2024, monthNum: 8,  month: "August",    setName: "Shrouded Fable",        setId: "sv6pt5",    promoName: "Pecharunt",               promoNum: "SVP129",  promoSetId: "svp",   promoCardNum: "129", pcEtbUrl: `${PC}/pokemon-shrouded-fable/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/pecharunt-pokemon-center-129`, notes: "Mini-set release." },
  { year: 2024, monthNum: 9,  month: "September", setName: "Stellar Crown",         setId: "sv7",       promoName: "Noctowl",                 promoNum: "SVP141",  promoSetId: "svp",   promoCardNum: "141", pcEtbUrl: `${PC}/pokemon-stellar-crown/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/noctowl-pokemon-center-141`, notes: "" },
  { year: 2024, monthNum: 11, month: "November",  setName: "Surging Sparks",        setId: "sv8",       promoName: "Magneton",                promoNum: "SVP159",  promoSetId: "svp",   promoCardNum: "159", pcEtbUrl: `${PC}/pokemon-surging-sparks/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/magneton-pokemon-center-159`, notes: "" },
  { year: 2025, monthNum: 1,  month: "January",   setName: "Prismatic Evolutions",  setId: "sv8pt5",    promoName: "Eevee",                   promoNum: "SVP173",  promoSetId: "svp",   promoCardNum: "173", pcEtbUrl: `${PC}/pokemon-prismatic-evolutions/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/eevee-pokemon-center-173`, notes: "Umbreon ex SIR is THE chase of the year." },
  { year: 2025, monthNum: 3,  month: "March",     setName: "Journey Together",      setId: "sv9",       promoName: "N's Zorua",               promoNum: "SVP189",  promoSetId: "svp",   promoCardNum: "189", pcEtbUrl: `${PC}/pokemon-journey-together/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/ns-zorua-pokemon-center-189`, notes: "First N's character set." },
  { year: 2025, monthNum: 5,  month: "May",       setName: "Destined Rivals",       setId: "sv10",      promoName: "Team Rocket's Wobbuffet", promoNum: "SVP203",  promoSetId: "svp",   promoCardNum: "203", pcEtbUrl: `${PC}/pokemon-destined-rivals/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/team-rockets-wobbuffet-pokemon-center-203`, notes: "Trainer-themed set." },
  { year: 2025, monthNum: 7,  month: "July",      setName: "Black Bolt",            setId: "zsv10pt5",  promoName: "Thundurus",               promoNum: "SVP209",  promoSetId: "svp",   promoCardNum: "209", pcEtbUrl: `${PC}/pokemon-black-bolt/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/thundurus-pokemon-center-209`, notes: "B/W remake duo - paired with White Flare." },
  { year: 2025, monthNum: 7,  month: "July",      setName: "White Flare",           setId: "rsv10pt5",  promoName: "Tornadus",                promoNum: "SVP210",  promoSetId: "svp",   promoCardNum: "210", pcEtbUrl: `${PC}/pokemon-white-flare/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/tornadus-pokemon-center-210`, notes: "B/W remake duo - paired with Black Bolt." },
  { year: 2025, monthNum: 9,  month: "September", setName: "Mega Evolution",        setId: "me1",       promoName: "Riolu",                   promoNum: "MEP010",  promoSetId: "mep",   promoCardNum: "10",  pcEtbUrl: `${PC}/pokemon-mega-evolution/elite-trainer-box-pokemon-center-mega-lucario`, pcPromoUrl: `${PC}/pokemon-promo/riolu-pokemon-center-10`, notes: "Mega Lucario variant ETB - Riolu PC promo." },
  { year: 2025, monthNum: 9,  month: "September", setName: "Mega Evolution",        setId: "me1",       promoName: "Alakazam",                promoNum: "MEP009",  promoSetId: "mep",   promoCardNum: "9",   pcEtbUrl: `${PC}/pokemon-mega-evolution/elite-trainer-box-pokemon-center-mega-gardevoir`, pcPromoUrl: `${PC}/pokemon-promo/alakazam-pokemon-center-9`, notes: "Mega Gardevoir variant ETB - Alakazam PC promo." },
  { year: 2025, monthNum: 11, month: "November",  setName: "Phantasmal Flames",     setId: "me2",       promoName: "Charcadet",               promoNum: "MEP022",  promoSetId: "mep",   promoCardNum: "22",  pcEtbUrl: `${PC}/pokemon-phantasmal-flames/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/charcadet-pokemon-center-22`, notes: "Mega Charizard X ex / Mega Gengar ex are top chases." },
  { year: 2026, monthNum: 1,  month: "January",   setName: "Ascended Heroes",       setId: "me2pt5",    promoName: "N's Zekrom",              promoNum: "MEP031",  promoSetId: "mep",   promoCardNum: "31",  pcEtbUrl: `${PC}/pokemon-ascended-heroes/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/n's-zekrom-pokemon-center-31`, notes: "Largest Mega-era set so far. Mega Gengar ex SIR and Pikachu ex SIR are top chases." },
  { year: 2026, monthNum: 3,  month: "March",     setName: "Perfect Order",         setId: "me3",       promoName: "Tyrunt",                  promoNum: "MEP070",  promoSetId: "mep",   promoCardNum: "70",  pcEtbUrl: `${PC}/pokemon-perfect-order/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/tyrunt-pokemon-center-70`, notes: "Tyrunt PC promo." },
  { year: 2026, monthNum: 5,  month: "May",       setName: "Chaos Rising",          setId: "me4",       promoName: "Fennekin",                promoNum: "MEP080",  promoSetId: "mep",   promoCardNum: "80",  pcEtbUrl: `${PC}/pokemon-chaos-rising/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/fennekin-pokemon-center-80`, notes: "Mega Greninja ex is the top chase." },
  { year: 2026, monthNum: 7,  month: "July",      setName: "Pitch Black",           setId: "me5",       promoName: "Zarude",                  promoNum: "MEP088",  promoSetId: "mep",   promoCardNum: "88",  pcEtbUrl: `${PC}/pokemon-pitch-black/elite-trainer-box-pokemon-center`, pcPromoUrl: `${PC}/pokemon-promo/zarude-pokemon-center-88`, notes: "Mega Darkrai ex is the top chase." },
  // PriceCharting has not catalogued the Pokemon Center-stamped Nidorina yet
  // (set released 2026-09-16). Only the unstamped in-set Nidorina #88 exists,
  // which is a different card, so pcPromoUrl stays empty and the promo price
  // reads as "—" rather than showing the wrong card's value. Fill it in once
  // PC lists pokemon-promo/nidorina-pokemon-center-101.
  { year: 2026, monthNum: 9,  month: "September", setName: "30th Celebration",      setId: "me55",      promoName: "Nidorina",                promoNum: "MEP101",  promoSetId: "mep",   promoCardNum: "101", pcEtbUrl: `${PC}/pokemon-30th-celebration/elite-trainer-box-pokemon-center`, pcPromoUrl: "", notes: "30th anniversary set. Nidorina promo (Pokedex #0030). Mew ex and Mewtwo ex are top chases." },
];

export const ETBS: ETB[] = RAW.map((e) => ({ ...e, era: eraOf(e.setId) }));

export function etbKey(e: Pick<ETB, "setId" | "promoNum">) {
  return `${e.setId}:${e.promoNum || "base"}`;
}
